

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { EmailContext } from './context/Emails-context'
import { UseEmailContext } from './context/Emails-context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={inter.className}>
          <useEmailContext>
            {children}
          </useEmailContext>
          </body>
    </html>
  )
}
